### ISSUE TITLE
Combining sync with async is sure possible

### ISSUE THREAD

**Issue by ar37-rs** [jczaja/train-helper#18]
@jczaja If you are interested and want to know how to do that properly, checkout the example: https://github.com/ar37-rs/eframe_tokio_app

**Comment by jczaja** [comment]
@ar37-rs Thanks for pointing me an example how to combine those two. So far I cameup with slighlty different approach #19  (each HTTP request is a future that I collect in Vec and then await them with join! and await). Those are my first steps in async world so hopefull I got better with time.
